import {readingUI} from './reading.mjs';
import {homeSections,services,reviews,quality,registration,registry,rules,laws,survey} from './sections.mjs';
import {privacy,personalData} from './legal.mjs';
export const escape = s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const phoneText = data=>String(data.phone||'+7 (921) 869-24-58');
export const phoneHref = data=>'tel:'+phoneText(data).replace(/[^\d+]/g,'');
export function dateText(value='2026-10-01'){
 const parts=String(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);
 if(!parts)return '1 октября 2026 года';
 const [year,month,day]=parts.slice(1).map(Number),date=new Date(Date.UTC(year,month-1,day));
 if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day)return '1 октября 2026 года';
 return `${day} ${['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'][month-1]} ${year} года`;
}
export const placeStats = data=>({free:99,planned:200,actual:101,date:'2026-10-01',...data.placeStats});
const paths={phone:'M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.69 2.79a2 2 0 0 1-.45 2.11L8.08 9.89a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.33 1.83.56 2.79.69A2 2 0 0 1 22 16.92Z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',chevron:'m6 9 6 6 6-6',download:'M12 3v12 m-5-5 5 5 5-5 M5 17v4h14v-4',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z M14 2v6h6 M8 13h8 M8 17h6',heart:'M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78Z',home:'m3 10 9-7 9 7 M5 9v12h14V9 M9 21v-8h6v8',mail:'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z m-2 2 10 7L22 6',clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M12 6v6l4 2',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',menu:'M3 6h18 M3 12h18 M3 18h18',close:'m6 6 12 12 M6 18 18 6',check:'m5 12 4 4L19 6',plus:'M12 5v14 M5 12h14',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M15 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',quote:'M3 10h6v8H2v-6c0-4 2-6 5-7 M16 10h6v8h-7v-6c0-4 2-6 5-7',external:'M15 3h6v6 M10 14 21 3 M21 14v7H3V3h7',left:'m14 6-6 6 6 6',right:'m10 6 6 6-6 6',zoom:'M15 11a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M11 8v6 M8 11h6 M21 21l-5-5 M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',calendar:'M8 2v4 M16 2v4 M3 10h18 M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6Z m-5 10 3 3 5-5'};
export function icon(name, cls=''){return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;}
export const routes=[
 ['index.html','Главная'],['services.html','Предоставление услуг'],['reviews.html','Отзывы'],
 ['survey.html','Онлайн-опрос'],['quality.html','Независимая оценка качества'],
 ['registration.html','Уведомление о постановке на учёт'],['registry.html','Лист записи ЕГРИП'],
 ['rules.html','Правила внутреннего распорядка'],['laws.html','Федеральные и областные законы'],
 ['privacy.html','Политика конфиденциальности'],['personal-data.html','Обработка персональных данных']
];
const anchor=(file,id)=>`${file}#${id}`;
function dropdown(label, links, current){return `<div class="nav-dropdown"><button class="nav-trigger ${links.some(([href])=>href.split('#')[0]===current)?'is-current':''}" aria-expanded="false">${label}${icon('chevron')}</button><div class="nav-panel" hidden>${links.map(([href,text])=>`<a href="${href}">${text}</a>`).join('')}</div></div>`;}
export function header(data, current){return `<a class="skip-link" href="#main">Перейти к содержанию</a>${readingUI()}<header class="site-header"><div class="container header-top"><a class="brand" href="index.html" aria-label="Заботливая услуга — главная"><img src="${escape(data.images.logo)}" alt="Заботливая услуга" width="108" height="83"><span>Социальная помощь <br> на дому в Пикалево</span></a><div class="header-actions"><button class="accessibility-button" data-accessibility aria-controls="reading-panel" aria-expanded="false" aria-label="Выбрать версию сайта">${icon('eye')}<span>Версия для слабовидящих</span></button><a class="header-phone" href="${escape(phoneHref(data))}" aria-label="Позвонить: ${escape(phoneText(data))}">${icon('phone')}<span>${escape(phoneText(data))}</span></a><a class="button button-small" href="index.html#feedback">Написать нам</a></div><button class="mobile-menu icon-button" aria-label="Открыть меню" aria-controls="site-nav" aria-expanded="false">${icon('menu')}</button></div><nav class="container site-nav" id="site-nav" aria-label="Основная навигация">${dropdown('Главная', [['index.html','Главная'],...[['about','О нас'],['places','Свободные места'],['news','Новости'],['faq','Вопросы и ответы'],['useful','Полезные ссылки'],['inspections','Информация о проверках'],['reports','Финансовая отчётность']].map(([id,title])=>[anchor('index.html',id),title])],current)}${dropdown('Предоставление услуг', [['services.html','Как получить помощь'],...[['types','Виды услуг'],['statistics','Численность и объём услуг'],['procedure','Порядок предоставления'],['tariffs','Тарифы на услуги'],['rules','Правила внутреннего распорядка']].map(([id,title])=>[anchor('services.html',id),title])],current)}<a class="nav-link ${current==='quality.html'?'is-current':''}" href="quality.html">Оценка качества</a><a class="nav-link ${current==='reviews.html'?'is-current':''}" href="reviews.html">Отзывы</a><a class="nav-link ${current==='survey.html'?'is-current':''}" href="survey.html">Онлайн-опрос</a>${dropdown('Документы',routes.slice(5,9),current)}<a class="nav-contact" href="index.html#contacts">Контакты${icon('pin')}</a></nav></header>`;}
export function footer(data){return `<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a href="index.html"><img src="${escape(data.images.logo)}" alt="Заботливая услуга" width="110" height="84"></a><p>ИП Левкович Е. С.</p></div><div><p class="footer-title">Свяжитесь с нами</p><a href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a><a href="mailto:${escape(data.email)}">${escape(data.email)}</a><span>Ежедневно, 10:00–19:00</span></div><div><p class="footer-title">Документы</p>${routes.slice(5,7).map(([href,title])=>`<a href="${href}">${title}</a>`).join('')}<a href="quality.html">Независимая оценка качества</a></div><div><p class="footer-title">Получателям услуг</p><a href="services.html">Предоставление услуг</a><a href="rules.html">Правила внутреннего распорядка</a><a href="laws.html">Федеральные и областные законы</a></div></div><div class="container footer-bottom"><span>Заботливая услуга · Пикалево, Ленинградская область</span><div class="footer-legal"><a href="privacy.html">Политика конфиденциальности</a><a href="personal-data.html">Обработка персональных данных</a></div><a href="#main">К началу страницы</a></div></footer>`;}
export function home(data){const stats=placeStats(data);return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">${icon('pin')}Пикалево · Ленинградская область</div><h1>Мы вам поможем<span>.</span></h1><p class="hero-description">Заботливая услуга — социальная помощь на дому людям пожилого возраста и людям с инвалидностью.</p><div class="hero-buttons"><a class="button" href="${escape(phoneHref(data))}">${icon('phone')}Позвонить нам</a><a class="button button-outline" href="services.html">Как получить помощь</a></div><div class="hero-hours">${icon('clock')}На связи ежедневно с 10:00 до 19:00</div></div><div class="hero-art" data-decoration><img src="${escape(data.images.hero)}" alt="" width="800" height="689" fetchpriority="high"></div></div><div class="container hero-facts"><a class="fact-places" href="#places">${icon('users')}<span><strong data-cms-ignore>${escape(stats.free)} свободных мест</strong><small data-cms-ignore>На ${escape(dateText(stats.date))}</small></span>${icon('chevron')}</a><div>${icon('home')}<span>Социальное обслуживание <strong>на дому</strong></span></div><div>${icon('heart')}<span>Помогаем <strong>с 2016 года</strong></span></div></div></section><section class="section" id="about"><div class="container about-grid"><div><h2>О нас</h2><p>В мае 2016 года в городе Пикалево начал работу социальный проект «Заботливая услуга». Мы помогаем пожилым людям и людям с инвалидностью в Пикалево и других городах и деревнях Ленинградской области.</p><p>Наша работа направлена на решение повседневных вопросов людей, которые частично или полностью утратили возможность самостоятельно обеспечивать свои жизненные потребности.</p><ul class="check-list"><li>Сотрудники с опытом социального обслуживания</li><li>Автомобиль для своевременной помощи</li><li>Специальная одежда и необходимый инвентарь</li></ul></div><div class="about-art" data-decoration><img src="${escape(data.images.care)}" alt="Ладони, поддерживающие сердце" width="426" height="426" loading="lazy"></div></div></section>`;}
export function documentCard(data,key,title,description=''){const doc=data.documents[key];const pdf=doc.format==='PDF';if(Object.hasOwn(doc,'title'))title=doc.title;if(Object.hasOwn(doc,'description'))description=doc.description;return `<a class="document-card" data-document="${escape(key)}" href="${escape(doc.src)}" target="_blank" rel="noopener noreferrer" ${pdf?'':'download'}><span class="document-symbol">${icon('file')}<small>${escape(doc.format)}</small></span><span class="document-content"><strong>${escape(title)}</strong>${description?`<span>${escape(description)}</span>`:''}<small>${escape(doc.format)} · ${doc.size>1048576?(doc.size/1048576).toFixed(1)+' МБ':Math.max(1,Math.round(doc.size/1024))+' КБ'}</small></span><span class="document-download">${icon(pdf?'external':'download')}<span class="sr-only">${pdf?'Открыть PDF в новой вкладке':'Скачать'}</span></span></a>`;}
export function pageHeading(title,desc=''){return `<section class="page-heading"><div class="container"><div class="breadcrumb"><a href="index.html">Главная</a><span>/</span><span>${title}</span></div><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</div></section>`;}
export function renderPage(data,file){
 const pages={'index.html':()=>home(data)+homeSections(data),'services.html':services,'reviews.html':reviews,'survey.html':survey,'quality.html':quality,'registration.html':registration,'registry.html':registry,'rules.html':rules,'laws.html':laws,'privacy.html':privacy,'personal-data.html':personalData};
 return file==='index.html'?pages[file]():pages[file](data);
}
