import {icon,documentCard,pageHeading,escape,phoneText,phoneHref,dateText,placeStats} from './pages.mjs';
const external=(url,label,cls='text-link')=>`<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${label}${icon('external')}</a>`;
const formConsent=(id,survey=false)=>`<div class="form-consent" ${survey?'data-survey-consent':''}><label class="consent" for="${id}"><input id="${id}" type="checkbox" name="consent" required><span>Согласен на <a href="personal-data.html" target="_blank" rel="noopener noreferrer">обработку персональных данных</a> на условиях <a href="privacy.html" target="_blank" rel="noopener noreferrer">политики конфиденциальности</a>.</span></label></div>`;
const honeypot=id=>`<div hidden aria-hidden="true" data-cms-ignore><label for="${id}-website">Не заполняйте это поле</label><input id="${id}-website" name="website" type="text" tabindex="-1" autocomplete="off"></div>`;
export function sectionTitle(label,title,detail=''){return `<div class="section-heading"><div><h2>${title}</h2></div>${detail?`<p>${detail}</p>`:''}</div>`;}
export const galleryCaptions={press:['Социальный бизнес — Заботливая услуга','Сотрудники «Заботливой услуги» получили заслуженные награды','За лучшую помощь пожилым людям','День добра и уважения','Газета «Рабочее слово»','Как Екатерина Левкович оценивает свою победу','Время победителей','Интервью с Екатериной Левкович'],thanks:['Благодарность наших подопечных, страница 1','Благодарность к 9 мая','Благодарность к 9 мая','Благодарность наших подопечных, страница 2'],poem:['Стихи Галины Фулжер'],awards:['Благодарность Дворца культуры г. Пикалево','Благодарственное письмо Союза женщин России','Благодарственное письмо, 2021 год','Благодарственное письмо, 2023 год','Диплом участника конкурса, 2018 год','Благодарственное письмо за помощь ветеранам','Диплом участника конкурса «Бизнес-признание»','Благодарственное письмо, ноябрь 2024 года','Благодарственное письмо администрации','Благодарность губернатора Ленинградской области','Благодарственное письмо, 2023 год']};
export const galleryTitles={press:'Публикации в прессе',thanks:'Благодарности наших подопечных',poem:'Стихи Галины Фулжер',awards:'Благодарственные письма и дипломы'};
export function gallery(data,key,title,description='',mode='rail'){
 const items=`<div class="gallery-items">${data.galleries[key].map((item,i)=>{const caption=Object.hasOwn(item,'caption')?item.caption:galleryCaptions[key]?.[i]||(title||galleryTitles[key])+' '+(i+1),alt=Object.hasOwn(item,'alt')?item.alt:caption;return `<a class="gallery-card" href="${escape(item.src)}" data-image-index="${i}" data-caption="${escape(caption)}" aria-label="Увеличить: ${escape(caption)}"><span class="gallery-image"><img src="${escape(item.thumb||item.src)}" alt="${escape(alt)}" loading="lazy" width="320" height="420"><span class="gallery-zoom">${icon('zoom')}</span></span><span class="gallery-caption"><span>${escape(caption)}</span><small>${String(i+1).padStart(2,'0')}</small></span></a>`}).join('')}</div>`;
 const stage=mode==='rail'?`<div class="gallery-stage"><button class="icon-button gallery-arrow" data-gallery-prev aria-label="Предыдущие публикации">${icon('left')}</button>${items}<button class="icon-button gallery-arrow" data-gallery-next aria-label="Следующие публикации">${icon('right')}</button></div>`:items;
 return `<div class="gallery gallery-${mode}" data-gallery="${escape(key)}"><div class="gallery-heading"><div>${title?'<h3>'+escape(title)+'</h3>':''}${description?`<p>${escape(description)}</p>`:''}</div></div>${stage}</div>`;
}
export function homeSections(data){const stats=placeStats(data);return `
<div class="container"><div class="notice about-notice">${icon('shield')}<div><p>Социальное обслуживание на дому рассчитано на <strong data-cms-ignore>${escape(stats.planned)} получателей</strong>. Услуги предоставляются за счёт бюджета Ленинградской области и за частичную плату по договорам за счёт средств физических лиц.</p><details><summary>Условия предоставления услуг</summary><p>Все социальные услуги предоставляются в соответствии с индивидуальной программой предоставления социальных услуг и на основании договора, соответствующего Федеральному закону от 28.12.2013 № 442-ФЗ «Об основах социального обслуживания граждан в Российской Федерации». Зарегистрированы на сайте Управления Федеральной службы по надзору в сфере связи, информационных технологий и массовых коммуникаций по Северо-Западному федеральному округу.</p><p>Оплата предоставленных социальных услуг рассчитывается на основании тарифов, утверждённых Постановлением Правительства Ленинградской области.</p></details></div></div></div>
<section class="section" id="press"><div class="container">${sectionTitle('','Публикации в прессе')}${gallery(data,'press','')}</div></section>
<section class="section section-soft" id="places"><div class="container">${sectionTitle('','Свободные места','Социальное обслуживание на дому. Данные на <span data-cms-ignore>'+escape(dateText(stats.date))+'</span>.')}<div class="places-layout"><div class="places-highlight"><div class="eyebrow">За счёт бюджета Ленинградской области</div><strong class="places-number" data-cms-ignore>${escape(stats.free)}</strong><span>свободных мест</span><a class="button" href="${escape(phoneHref(data))}">${icon('phone')}Уточнить наличие мест</a></div><div class="places-stats"><div class="stat-line"><span>Плановая численность получателей</span><strong data-cms-ignore>${escape(stats.planned)}</strong></div><div class="stat-line"><span>Фактическая численность получателей</span><strong data-cms-ignore>${escape(stats.actual)}</strong></div><details class="paid-places"><summary>За счёт средств физических и юридических лиц</summary><dl><div><dt>Плановая численность</dt><dd>0</dd></div><div><dt>Фактическая численность</dt><dd>0</dd></div><div><dt>Свободных мест</dt><dd>0</dd></div></dl></details><p class="small-note">В течение месяца наличие свободных мест можно уточнить по телефону <a href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a>.</p></div></div></div></section>
<section class="section" id="news"><div class="container">${sectionTitle('','Новости')}<div class="news-grid"><article class="news-card"><span class="news-icon">${icon('home')}</span><div class="eyebrow">Комитет по социальной защите населения</div><h3>Пункты проката средств реабилитации</h3><p>Во всех муниципальных районах Ленинградской области работают пункты проката технических средств реабилитации. Временно получить их могут люди с инвалидностью, а также люди, попавшие в трудную жизненную ситуацию.</p><p>Адреса, телефоны пунктов и перечень доступных средств размещены на официальном сайте комитета.</p>${external(data.links.rentals,'Адреса пунктов проката','button button-outline')}</article><article class="news-card"><span class="news-icon">${icon('users')}</span><h3>Исследование социальных услуг</h3><p>Ленинградский фонд поддержки предпринимательства совместно с Санкт-Петербургским государственным университетом проводит исследование развития социального предпринимательства в Ленинградской области.</p><p>Если вы пользовались услугами в сферах здравоохранения, образования, социального обслуживания, спорта, отдыха, развлечений или культуры с 2022 по 2024 год, примите участие в опросе. Доступность этих услуг влияет на образование, здоровье, отдых и качество жизни.</p>${external(data.links.researchSurvey,'Пройти исследовательский опрос','button button-outline')}</article></div></div></section>
<section class="section section-soft" id="faq"><div class="container faq-layout"><div><h2>Вопросы и ответы</h2><a class="text-link" href="${escape(phoneHref(data))}">${icon('phone')}${escape(phoneText(data))}</a></div><div class="accordion">${data.faq.map((q,i)=>`<details ${i===0?'open':''}><summary>${escape(q.question)}${icon('plus')}</summary><div class="accordion-body">${q.answer.map(p=>`<p>${escape(p)}</p>`).join('')}</div></details>`).join('')}</div></div></section>
<section class="section" id="useful"><div class="container">${sectionTitle('','Полезные ссылки')}<div class="resource-grid">${[
 ['gosu','Госуслуги','gosuslugi.ru','https://www.gosuslugi.ru/'],
 ['mintrud','Минтруд России','mintrud.gov.ru','https://mintrud.gov.ru/'],
 ['socdef','Портал социальной защиты населения Ленинградской области','soczaschita.lenobl.ru','https://soczaschita.lenobl.ru/'],
 ['komitet','Комитет по социальной защите населения Ленинградской области','social.lenobl.ru','https://social.lenobl.ru/'],
 ['cszn','ЛОГКУ «Центр социальной защиты населения»','cszn.info','https://cszn.info/']
 ].map(([img,title,url,href])=>`<a class="resource-card" href="${href}" target="_blank" rel="noopener noreferrer"><img src="${escape(data.images[img])}" alt="" width="66" height="66" loading="lazy"><span><strong>${title}</strong><small>${url}</small></span>${icon('external')}</a>`).join('')}</div></div></section>
<section class="section section-soft" id="inspections"><div class="container">${sectionTitle('Открытая информация','Информация о проверках','Предписания органов государственного контроля в сфере социального обслуживания.')}<div class="documents-grid">${documentCard(data,'warning','Предостережение о недопустимости нарушения обязательных требований')}${documentCard(data,'warningReport','Отчёт об исполнении предостережения № 67','От 17 сентября 2024 года')}</div></div></section>
<section class="section" id="reports"><div class="container">${sectionTitle('Открытая информация','Финансовая отчётность')}<div class="documents-grid">${documentCard(data,'finance2023','Декларация за 2023 год')}${documentCard(data,'finance2024','Декларация за 2024 год')}</div></div></section>
<section class="section feedback-section" id="feedback"><div class="container feedback-grid"><div><h2>Написать нам</h2><a class="feedback-phone" href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a><p class="small-note">Ежедневно с 10:00 до 19:00</p></div><form id="feedback-form" action="/api/contact" method="post"><div class="form-row"><label for="feedback-name">Ваше имя</label><input id="feedback-name" name="name" placeholder="Как к вам обращаться" autocomplete="name" required maxlength="120"></div><div class="form-row"><label for="feedback-phone">Телефон <span>необязательно</span></label><input id="feedback-phone" name="phone" type="tel" inputmode="numeric" placeholder="+7 (___) ___-__-__" autocomplete="tel" pattern="\\+7 \\([0-9]{3}\\) [0-9]{3}-[0-9]{2}-[0-9]{2}" maxlength="30"></div><div class="form-row"><label for="feedback-message">Сообщение</label><textarea id="feedback-message" name="message" placeholder="Напишите, чем мы можем помочь" rows="4" required maxlength="4000"></textarea></div>${formConsent('feedback-consent')}${honeypot('feedback')}<div class="form-bottom"><button class="button" type="submit">${icon('mail')}Отправить</button></div><p class="form-status" data-form-status role="status" aria-live="polite" hidden></p></form></div></section>
<section class="section" id="contacts"><div class="container">${sectionTitle('','Контакты')}<div class="contact-grid"><div class="contact-card">${icon('pin')}<h3>Где мы находимся</h3><p>Ленинградская область, <br> Бокситогорский район, <br> ул. Больничная, 20</p></div><div class="contact-card">${icon('clock')}<h3>Режим работы</h3><p>Ежедневно <br> <strong>10:00–19:00</strong></p></div><div class="contact-card">${icon('users')}<h3>Руководитель</h3><p>Левкович <br> Екатерина Сергеевна</p></div><div class="contact-card">${icon('phone')}<h3>Связаться с нами</h3><a href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a><a href="mailto:${escape(data.email)}">${escape(data.email)}</a></div></div></div></section>`;}

export function services(data){return `${pageHeading('Предоставление услуг','Помощь на дому с учётом ваших потребностей и индивидуальной программы социальных услуг.')}<div class="container page-jump-links" aria-label="Разделы страницы"><a href="#getting">Как получить помощь</a><a href="#types">Виды услуг</a><a href="#statistics">Численность и объём</a><a href="#procedure">Порядок</a><a href="#tariffs">Тарифы</a><a href="#rules">Правила</a></div>
<section class="section" id="getting"><div class="container">${sectionTitle('С чего начать','Как получить помощь')}<p class="intro-text">Социальное обслуживание осуществляется с добровольного согласия граждан пожилого возраста и людей с инвалидностью на получение социальных услуг.</p><div class="steps-grid"><article class="step-card"><span class="step-number">01</span><h3>Подайте заявление</h3><p>Обратитесь в центр социальной защиты населения или МФЦ для признания нуждаемости и получения индивидуальной программы предоставления социальных услуг (ИППСУ).</p></article><article class="step-card"><span class="step-number">02</span><h3>Подготовьте документы</h3><p>ИППСУ, копию документа, удостоверяющего личность, и документ о полномочиях законного представителя, если он обращается от вашего имени.</p></article><article class="step-card"><span class="step-number">03</span><h3>Заключите договор</h3><p>В договоре указываются согласованные услуги в соответствии с ИППСУ и условия обслуживания: бесплатно или с частичной оплатой.</p></article></div><div class="service-info-grid"><div class="prose"><h3>Основание для предоставления услуг</h3><p>Основанием является поданное заявление гражданина или его законного представителя о предоставлении социального обслуживания либо обращение в его интересах иных граждан, государственных органов, органов местного самоуправления или общественных объединений к поставщику социальных услуг.</p><details class="plain-details"><summary>Когда может измениться размер платы</summary><p>Размер платы за социальные услуги, установленный договором, может меняться при изменении:</p><ul><li>среднедушевого дохода получателя социальных услуг;</li><li>величины прожиточного минимума в Ленинградской области для основных социально-демографических групп населения;</li><li>тарифов на социальные услуги;</li><li>видов и (или) объёма предоставляемых услуг.</li></ul></details></div><div>${documentCard(data,'sampleContract','Образец договора','О предоставлении социальных услуг')}<div class="notice compact-notice">${icon('phone')}<p>Поможем разобраться с документами. <br> <a href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a></p></div></div></div></div></section>
<section class="section section-soft" id="types"><div class="container service-types-layout"><div><h2>Виды социальных услуг</h2><p>Форма социального обслуживания — на дому.</p></div><div class="accordion service-accordion">${data.services.map((s,i)=>`<details ${i===0?'open':''}><summary><span class="service-type-icon">${icon(['home','heart','users','shield'][i])}</span>${escape(s.title)}${icon('plus')}</summary><div class="accordion-body"><ul>${s.items.map(item=>`<li>${escape(item)}</li>`).join('')}</ul></div></details>`).join('')}</div></div></section>
<section class="section" id="statistics"><div class="container">${sectionTitle('','Численность и объём услуг','Социальное обслуживание на дому.')}<div class="summary-stats"><div><strong>101</strong><span>получатель социальных услуг</span></div><div><strong>8 349</strong><span>предоставленных услуг</span></div></div>${[['recipients-panel',[101,101,101,0,101],'Численность получателей услуг','Количество получателей, человек'],['volume-panel',[5895,1708,746,0,8349],'Объём предоставленных услуг','Количество услуг']].map(([id,values,title,unit],k)=>`<div class="statistics-block"><h3 id="${id}-title">${title}</h3><p class="table-hint" data-cms-ignore>Прокрутите таблицу в сторону, чтобы увидеть все данные.</p><div class="table-wrap" role="region" id="${id}" aria-labelledby="${id}-title" tabindex="0"><table><caption class="sr-only">Данные за сентябрь 2026 года. ${unit}.</caption><thead><tr><th scope="col">Виды услуг</th><th scope="col">За счёт бюджета Ленинградской области</th><th scope="col">За счёт средств физических и юридических лиц по договорам</th></tr></thead><tbody>${['Социально-бытовые','Социально-медицинские','Социально-психологические','Социально-правовые','Итого'].map((label,i)=>`<tr class="${i===4?'table-total':''}"><th scope="row">${label}${i<4?' услуги':''}</th><td>${values[i].toLocaleString('ru-RU')}</td><td>0</td></tr>`).join('')}</tbody></table></div>${k?'':'<p class="small-note">Количество получателей по видам услуг не суммируется: один человек может получать несколько видов помощи.</p>'}</div>`).join('')}</div></section>
<section class="section section-soft" id="procedure"><div class="container split-section"><div><h2>Порядок предоставления услуг</h2><p>Кто имеет право на помощь, как получить ИППСУ и какие документы понадобятся.</p><button class="button" data-dialog="procedure">${icon('file')}Читать порядок</button></div><div>${documentCard(data,'decree536','Постановление № 536 от 29.07.2022','Порядок предоставления социальных услуг в Ленинградской области')}</div></div></section>
<section class="section" id="tariffs"><div class="container">${sectionTitle('Тарифы на услуги','Стоимость и условия оплаты','Услуги могут предоставляться бесплатно или с частичной оплатой в зависимости от категории и дохода получателя.')}<div class="tariffs-layout"><div class="tariff-card">${icon('heart')}<h3>Кому услуги предоставляются бесплатно</h3><p>О категориях получателей, расчёте платы и порядке оплаты.</p><button class="button button-outline" data-dialog="tariffs">Читать условия</button></div><div class="document-list"><a class="document-card" href="${escape(data.links.decree2026)}" target="_blank" rel="noopener noreferrer"><span class="document-symbol">${icon('file')}<small>2026</small></span><span class="document-content"><strong>Постановление № 986</strong><span>Об утверждении тарифов на социальные услуги на 2026 год</span><small>Документ в Google Drive</small></span>${icon('external')}</a><a class="document-card" href="${escape(data.links.rates2026)}" target="_blank" rel="noopener noreferrer"><span class="document-symbol">${icon('file')}<small>2026</small></span><span class="document-content"><strong>Тарифы на 2026 год</strong><span>Таблица стоимости социальных услуг</span><small>Google Таблицы</small></span>${icon('external')}</a></div></div></div></section>
<section class="section section-soft" id="rules"><div class="container split-section"><div><h2>Правила внутреннего распорядка</h2></div><div>${documentCard(data,'rules','Правила внутреннего распорядка')}<a class="text-link secondary-link" href="rules.html">Открыть страницу документа</a></div></div></section>
<template id="dialog-procedure"><div class="dialog-label">Предоставление услуг</div><h2 id="dialog-title">Порядок предоставления социальных услуг</h2><div class="prose dialog-prose">${data.procedure}</div></template><template id="dialog-tariffs"><div class="dialog-label">Тарифы и оплата</div><h2 id="dialog-title">Тарифы на социальные услуги</h2><div class="prose dialog-prose">${data.tariffs}</div></template>`;}

export function reviews(data){return `${pageHeading('Отзывы','Благодарности наших подопечных, стихи и благодарственные письма.')}<section class="section"><div class="container">${gallery(data,'thanks','Благодарности наших подопечных','Письма людей, которым мы помогаем. Нажмите на изображение, чтобы прочитать его полностью.','grid')}</div></section><section class="section section-soft"><div class="container poem-section"><div><h2>Стихи Галины Фулжер</h2>${icon('quote','poem-quote')}</div>${gallery(data,'poem','','','grid')}</div></section><section class="section"><div class="container">${gallery(data,'awards','Благодарственные письма и дипломы','','grid')}</div></section>`;}

export function quality(data){return `${pageHeading('Независимая оценка качества','Ваша оценка поможет улучшить условия предоставления социальных услуг.')}<section class="section"><div class="container quality-layout"><div><h2>Оценить качество услуг</h2><p>Оцените условия предоставления услуг или оставьте обращение на официальном портале bus.gov.ru.</p><p>Откройте анкету по прямой ссылке. Если вы смотрите сайт с компьютера, можно навести камеру телефона на QR-код.</p>${external(data.links.quality,'Оценить качество услуг','button')}<div class="quality-url">bus.gov.ru/qrcode/rate/789838</div></div><div class="qr-card"><img src="${escape(data.images.qr)}" alt="QR-код анкеты независимой оценки качества на bus.gov.ru" width="271" height="271"><p>Наведите камеру телефона</p></div></div></section><section class="section section-soft"><div class="container">${sectionTitle('Результаты оценки','Документы НОК')}<div class="document-list narrow">${documentCard(data,'quality','Независимая оценка качества за 2023 год','С планом устранения недостатков')}</div></div></section>`;}

export function registration(data){return `${pageHeading('Уведомление о постановке на учёт','Документ о постановке индивидуального предпринимателя на учёт в налоговом органе.')}<section class="section document-page"><div class="container document-layout"><aside><h3>ИП Левкович <br> Екатерина Сергеевна</h3><dl class="document-meta"><div><dt>Дата постановки на учёт</dt><dd>12 апреля 2021 года</dd></div><div><dt>ИНН</dt><dd>472200037102</dd></div><div><dt>ОГРНИП</dt><dd>321470400033587</dd></div></dl><a class="button button-outline" href="${escape(data.images.registration)}" download="Уведомление-о-постановке-на-учет.jpg">${icon('download')}Скачать документ</a><p class="small-note">Нажмите на изображение для увеличения.</p></aside><div class="scan-stack" data-gallery="registration"><a class="scan-image" href="${escape(data.images.registration)}" data-image-index="0" data-caption="Уведомление о постановке на учёт" aria-label="Увеличить уведомление о постановке на учёт"><img src="${escape(data.images.registration)}" alt="Уведомление о постановке ИП Левкович Екатерины Сергеевны на учёт, от 13.04.2021" width="1680" height="2375"><span class="scan-zoom">${icon('zoom')}Увеличить документ</span></a></div></div></section>`;}

export function registry(data){return `${pageHeading('Лист записи ЕГРИП','Единый государственный реестр индивидуальных предпринимателей.')}<section class="section document-page"><div class="container document-layout"><aside><h3>ИП Левкович <br> Екатерина Сергеевна</h3><dl class="document-meta"><div><dt>Дата регистрации</dt><dd>12 апреля 2021 года</dd></div><div><dt>ОГРНИП</dt><dd>321470400033587</dd></div><div><dt>Основной вид деятельности</dt><dd>88.10 — предоставление социальных услуг без обеспечения проживания престарелым и инвалидам</dd></div><div><dt>Дополнительный вид деятельности</dt><dd>87.90 — деятельность по уходу с обеспечением проживания прочая</dd></div></dl><div class="download-stack"><a class="button button-outline" href="${escape(data.images.registry1)}" download="Лист-записи-ЕГРИП-1.jpg">${icon('download')}Скачать страницу 1</a><a class="button button-outline" href="${escape(data.images.registry2)}" download="Лист-записи-ЕГРИП-2.jpg">${icon('download')}Скачать страницу 2</a></div></aside><div class="scan-stack" data-gallery="registry">${[1,2].map((n,i)=>`<a class="scan-image" href="${escape(data.images['registry'+n])}" data-image-index="${i}" data-caption="Лист записи ЕГРИП — страница ${n}" aria-label="Увеличить страницу ${n} листа записи ЕГРИП"><img src="${escape(data.images['registry'+n])}" alt="Лист записи ЕГРИП, страница ${n}" width="1680" height="2375" loading="${i?'lazy':'eager'}"><span class="scan-zoom">${icon('zoom')}Страница ${n} · Увеличить</span></a>`).join('')}</div></div></section>`;}

export function rules(data){return `${pageHeading('Правила внутреннего распорядка','Документ для получателей социальных услуг.')}<section class="section"><div class="container rules-layout"><div class="rules-illustration">${icon('file')}</div><div><h2>Правила обслуживания</h2><p>Правила внутреннего распорядка для получателей социальных услуг доступны в документе Word.</p>${documentCard(data,'rules','Правила внутреннего распорядка для получателей социальных услуг')}<div class="notice compact-notice">${icon('phone')}<p>Если остались вопросы, позвоните нам: <br> <a href="${escape(phoneHref(data))}">${escape(phoneText(data))}</a></p></div></div></div></section>`;}

export function laws(data){return `${pageHeading('Федеральные и областные законы','Нормативные документы, регулирующие предоставление социальных услуг.')}<section class="section"><div class="container laws-layout"><aside class="laws-sidebar"><div class="eyebrow">Документы</div><p>Федеральное законодательство и документы Ленинградской области.</p><a class="text-link" href="services.html#procedure">Порядок получения услуг</a></aside><div class="document-list">${documentCard(data,'contract','Приказ Минтруда России от 10.11.2014 № 874н','О примерной форме договора о предоставлении социальных услуг и форме индивидуальной программы')}${documentCard(data,'law442','Федеральный закон от 28.12.2013 № 442-ФЗ','Об основах социального обслуживания граждан в Российской Федерации')}${documentCard(data,'application','Приказ Минтруда России от 28.03.2014 № 159н','Об утверждении формы заявления о предоставлении социальных услуг')}${documentCard(data,'decree606','Постановление Правительства Ленинградской области от 22.12.2017 № 606','Об утверждении порядков предоставления социальных услуг поставщиками в Ленинградской области')}${documentCard(data,'law72','Областной закон от 30.10.2014 № 72-оз','О социальном обслуживании граждан в Ленинградской области')}${documentCard(data,'decree536','Постановление Правительства Ленинградской области от 29.07.2022 № 536','Об утверждении порядка предоставления социальных услуг поставщиками в Ленинградской области')}</div></div></section>`;}

export const questions=[
 ['Как вы оцениваете качество, полноту и доступность информации о работе организации социального обслуживания, в которой получаете услуги?', 'При личном обращении, по телефону и на официальном сайте.', ['Отлично, всё устраивает','В целом хорошо','Удовлетворительно, незначительные недостатки','Плохо, много недостатков','Неудовлетворительно, совершенно не устраивает','Затрудняюсь ответить']],
 ['Работники организации социального обслуживания, предоставляющие вам услуги, доброжелательны, вежливы, внимательны?', '', ['Да','Нет','Затрудняюсь ответить']],
 ['Вы удовлетворены компетентностью работников организации социального обслуживания, в которой получаете услуги?', '', ['Полностью удовлетворён','Скорее удовлетворён','В чём-то удовлетворён, в чём-то нет','Скорее не удовлетворён','Совершенно не удовлетворён','Затрудняюсь ответить']],
 ['Удовлетворяют ли вас условия предоставления социальных услуг?', '', ['Отлично, всё устраивает','В целом хорошо','Удовлетворительно, незначительные недостатки','Плохо, много недостатков','Неудовлетворительно, совершенно не устраивает','Затрудняюсь ответить']],
 ['Посоветуете ли вы своим родственникам или знакомым, нуждающимся в социальном обслуживании, обратиться в нашу организацию?', '', ['Точно порекомендую','Скорее порекомендую','Скорее не порекомендую','Точно не порекомендую','Затрудняюсь ответить']],
 ['Ваши предложения и пожелания по улучшению качества предоставляемых социальных услуг', 'Необязательно', null]
];
export function survey(data){return `${pageHeading('Онлайн-опрос','Оцените качество предоставления социальных услуг.')}<section class="section survey-section"><div class="container survey-container"><div class="survey-top"><span>Поставщик услуг: <br> <strong>ИП Левкович Екатерина Сергеевна</strong></span><div class="survey-view" aria-label="Вид опроса"><button type="button" data-survey-mode="steps" aria-pressed="true">Пошагово</button><button type="button" data-survey-mode="all" aria-pressed="false">Все вопросы</button></div></div><form id="survey-form" action="/api/survey" method="post" data-mode="all"><div class="survey-progress" hidden><div class="survey-progress-label"><span id="survey-counter">Вопрос 1 из 6</span><span>Оценка качества услуг</span></div><div role="progressbar" aria-label="Ход опроса" aria-valuemin="1" aria-valuemax="6" aria-valuenow="1"><span style="width:16.6667%"></span></div></div>${questions.map(([question,note,options],i)=>`<fieldset class="survey-step" data-step="${i}"><legend><span class="question-number">${String(i+1).padStart(2,'0')}</span><span>${question}${note?`<small>${note}</small>`:''}</span></legend>${options?`<div class="survey-options">${options.map((o,j)=>`<label class="radio-option"><input type="radio" name="question${i+1}" value="${escape(o)}" ${j===0?'required':''}><span>${o}</span></label>`).join('')}</div>`:`<textarea name="wishes" aria-label="Предложения и пожелания" rows="5" placeholder="Расскажите, что можно улучшить" maxlength="3000"></textarea>`}</fieldset>`).join('')}<p class="survey-error" role="alert" hidden>Выберите вариант ответа, чтобы продолжить.</p>${formConsent('survey-consent',true)}${honeypot('survey')}<div class="survey-actions"><button type="button" class="button button-outline" data-survey-back hidden>Назад</button><span class="survey-send-note">Результаты публикуются в общем виде. Пожелания доступны только администратору.</span><button type="button" class="button" data-survey-next hidden>Далее</button><button type="submit" class="button" data-survey-submit>Отправить</button></div><p class="form-status" data-form-status role="status" aria-live="polite" hidden></p></form><p class="form-status is-success" id="survey-complete" role="status" aria-live="polite" hidden></p></div></section><section class="section section-soft" id="survey-results"><div class="container survey-results-container"><h2>Результаты опроса</h2><p class="survey-results-summary" hidden data-results-summary>Всего ответов: <strong data-results-total></strong><span data-results-updated hidden></span></p><p class="form-status" role="status" aria-live="polite" data-results-status>Загрузка результатов…</p><button class="button button-outline" type="button" data-results-retry hidden>Обновить результаты</button><div class="survey-result-questions" data-results-questions data-cms-ignore></div></div></section>`;}
